example/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.admindocs import urls as docs_urls
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from simpel_pages.sitemaps import CategorySitemap, PageSitemap, SearchSitemap, TagSitemap

sitemaps = {
    "pages": PageSitemap,
    "categories": CategorySitemap,
    "tags": TagSitemap,
    "search": SearchSitemap,
}

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("admin/docs/", include(docs_urls)),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="page_sitemap"),
    path("", include("simpel_pages.urls")),
    prefix_default_language=False,
)

simpel_pages/urls.py
from django.urls import re_path

from . import views
from .settings import pages_settings

if pages_settings.APPEND_SLASH:
    # If APPEND_SLASH is True (the default value), we match a
    # (possibly empty) list of path segments ending in slashes.
    # CommonMiddleware will redirect requests without a trailing slash to
    # a URL with a trailing slash
    serve_pattern = r"^((?:[\w\-]+/)*)$"
else:
    # If WAGTAIL_APPEND_SLASH is False, allow Wagtail to serve pages on URLs
    # with and without trailing slashes
    serve_pattern = r"^([\w\-/]*)$"

urlpatterns = [
    re_path(r"^tag/$", views.serve_tags, name="serve_tag"),
    re_path(r"^tag/(?P<slug>[-\w]+)/$", views.serve_tag, name="serve_tag"),
    re_path(r"^category/$", views.serve_categories, name="serve_category"),
    re_path(r"^category/(?P<slug>[-\w]+)/$", views.serve_category, name="serve_category"),
    re_path(r"^search/(?P<slug>[-\w]+)/$", views.serve_search, name="serve_search"),
    re_path(r"^search/", views.serve_search, name="serve_search"),
    re_path(serve_pattern, views.serve_page, name="serve_pages"),
]

simpel_pages/models/pages.py
import logging

from django.apps import apps
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.contrib.auth.views import redirect_to_login
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.db import models
from django.http.response import Http404, HttpResponse
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView

from filer.fields.image import FilerImageField
from mptt.models import MPTTModel, TreeForeignKey
from simpel_themes.models import ModelTemplate
from taggit.managers import TaggableManager
from taggit.models import TagBase, TaggedItemBase
from tinymce.models import HTMLField

from simpel_pages.managers import CategoryManager, PageManager, TagManager
from simpel_pages.utils import unique_slugify

from ..routable import RouteResult
from ..settings import pages_settings

logger = logging.getLogger(__name__)


class IndexView(ListView):
    page_template = None

    def render_to_response(self, context, **response_kwargs):
        return HttpResponse(self.page_template.render(context, self.request))


class Category(MPTTModel):

    parent = TreeForeignKey(
        "self",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="children",
        help_text=_(
            "Categories, unlike tags, can have a hierarchy. You might have a "
            "Jazz category, and under that have children categories for Bebop"
            " and Big Band. Totally optional."
        ),
    )
    thumbnail = FilerImageField(
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="pagecategories",
    )
    name = models.CharField(
        max_length=80,
        unique=True,
        verbose_name=_("Category Name"),
    )
    description = HTMLField(
        null=True,
        blank=True,
        verbose_name=_("Description"),
    )
    slug = models.SlugField(
        unique=True,
        null=True,
        blank=True,
        editable=False,
        max_length=80,
    )
    seo_title = models.CharField(
        _("SEO title"),
        null=True,
        blank=True,
        max_length=200,
    )
    seo_description = models.TextField(
        _("SEO description"),
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(default=timezone.now)
    last_modified_at = models.DateTimeField(default=timezone.now)
    visitor_count = models.IntegerField(default=0)
    objects = CategoryManager()
    icon = "tag-outline"

    class Meta:
        ordering = ["name"]
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        permissions = (
            ("import_category", _("Can import Category")),
            ("export_category", _("Can export Category")),
        )

    def __str__(self):
        return self.name

    @property
    def opts(self):
        return self.__class__._meta

    @property
    def title(self):
        return self.name

    def get_absolute_url(self):
        return reverse("serve_category", kwargs={"slug": self.slug})

    def clean(self):
        if self.parent:
            parent = self.parent
            if self.parent == self:
                raise ValidationError("Parent category cannot be self.")
            if parent.parent and parent.parent == self:
                raise ValidationError("Cannot have circular Parents.")

    def save(self, *args, **kwargs):
        if not self.slug:
            unique_slugify(self, self.name)
        if not self.seo_title:
            self.seo_title = "%s Category" % self.name
        return super().save(*args, **kwargs)


class Tag(TagBase):

    thumbnail = FilerImageField(
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="pagetags",
    )
    description = HTMLField(
        null=True,
        blank=True,
        verbose_name=_("Description"),
    )
    seo_title = models.CharField(
        _("SEO title"),
        null=True,
        blank=True,
        max_length=200,
    )
    seo_description = models.TextField(
        _("SEO description"),
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(default=timezone.now)
    last_modified_at = models.DateTimeField(default=timezone.now)
    visitor_count = models.IntegerField(default=0)
    icon = "tag-outline"

    objects = TagManager()

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    @property
    def opts(self):
        return self._meta

    @property
    def title(self):
        return self.name

    def get_absolute_url(self):
        return reverse("serve_tag", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.seo_title:
            self.seo_title = "%s Tag" % self.name
        return super().save(*args, **kwargs)


class Page(MPTTModel):
    created_at = models.DateTimeField(
        default=timezone.now,
        verbose_name=_("Created at"),
    )
    updated_at = models.DateTimeField(
        default=timezone.now,
        verbose_name=_("Last updated at"),
    )
    published_at = models.DateTimeField(
        default=timezone.now,
        verbose_name=_("First published at"),
    )
    owner = models.ForeignKey(
        get_user_model(),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="pages",
        verbose_name=_("Page Owner"),
    )
    parent = TreeForeignKey(
        "self",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="childs",
        help_text=_(
            "Pages, unlike tags, can have a hierarchy. You might have a "
            "Index page, and under that have children pages for post"
            " and story. Totally optional."
        ),
    )
    title = models.CharField(
        _("title"),
        max_length=200,
    )
    category = TreeForeignKey(
        Category,
        related_name="pages",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("Category"),
    )
    tags = TaggableManager(
        through="TaggedPage",
        blank=True,
        related_name="pages",
        verbose_name=_("Tags"),
    )
    thumbnail = FilerImageField(
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="simpelpages",
    )
    content = HTMLField(
        null=True,
        blank=True,
        verbose_name=_("Content"),
    )
    data = models.JSONField(null=True, blank=True)
    slug = models.SlugField(
        unique=True,
        null=True,
        blank=True,
        db_index=True,
        max_length=255,
    )
    seo_title = models.CharField(
        _("SEO title"),
        null=True,
        blank=True,
        max_length=200,
    )
    seo_description = models.TextField(
        _("SEO description"),
        null=True,
        blank=True,
    )
    template = models.ForeignKey(
        ModelTemplate,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="%(class)s_templates",
        verbose_name=_("Template"),
    )
    url_path = models.CharField(
        max_length=255,
        null=True,
        blank=True,
    )
    index = models.BooleanField(
        _("index"),
        default=False,
        help_text=_("Index page, contain child pages and not included in widgets."),
    )
    per_page = models.IntegerField(
        default=0,
        verbose_name=_("per page"),
        help_text=_("Number item per page, used only when index is True."),
    )
    live = models.BooleanField(
        _("live"),
        default=True,
    )
    show_in_menu = models.BooleanField(
        _("show in menu"),
        default=False,
    )
    allow_comments = models.BooleanField(
        _("allow comments"),
        default=False,
    )
    registration_required = models.BooleanField(
        _("registration required"),
        help_text=_("If this is checked, only logged-in users will be able to view the page."),
        default=False,
    )
    groups = models.ManyToManyField(
        Group,
        verbose_name=_("groups"),
        blank=True,
        related_name="+",
        help_text=_(
            "The groups this menu belongs to. A menu will get all permissions " "granted to each of their groups."
        ),
    )
    real_model = models.CharField(
        max_length=120,
        editable=False,
        null=True,
        blank=True,
    )
    readers = models.ManyToManyField(
        get_user_model(),
        blank=True,
        related_name="page_readers",
        verbose_name=_("Users who mark this page as read."),
    )
    bookmarks = models.ManyToManyField(
        get_user_model(),
        blank=True,
        related_name="bookmarks",
        verbose_name=_("Users who bookmark this page."),
    )
    visitor_count = models.IntegerField(default=0)

    objects = PageManager()

    class Meta:
        ordering = ["-created_at"]

    def has_submenu(self):
        return self.get_submenu().count()

    def get_submenu(self):
        return self.get_descendants(include_self=False).filter(show_in_menu=True)

    def get_descendants(self, include_self=False):
        return super().get_descendants(include_self)

    def get_blocks(self):
        model = self.get_real_model_class()
        ctype = ContentType.objects.get_for_model(model)
        blocks = ctype.blocks.filter(object_id=self.id).order_by("position")
        return blocks

    def __str__(self):
        return "%s" % self.title

    @property
    def opts(self):

simpel_pages/forms.py
from django import forms

from tinymce.widgets import TinyMCE

from .models import Page


class PageForm(forms.ModelForm):
    content = TinyMCE(
        attrs={"cols": 80, "rows": 20, "height": 97},
        mce_attrs={"height": 300},
    )

    class Meta:
        model = Page
        fields = "__all__"

simpel_pages/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.http import Http404, HttpResponse, QueryDict
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_protect
from django.views.generic.list import ListView

from haystack.views import SearchView
from simpel_hookup import core as hookup
from tinymce.views import render_to_link_list

from .helpers import log_traffic
from .models import Category, RootPage, Tag
from .models.pages import Page, SearchQuery
from .settings import pages_settings


@csrf_protect
def serve_page(request, path):
    # we need a valid Site object corresponding to this request in order to proceed
    site = get_current_site(request)
    if not site:
        raise Http404

    path_components = [component for component in path.split("/") if component]
    site_root = RootPage.objects.get(site=site)
    page, args, kwargs = site_root.page.specific.route(request, path_components)

    for fn in hookup.get_hooks("PAGES_BEFORE_SERVE"):
        result = fn(page, request, args, kwargs)
        if isinstance(result, HttpResponse):
            return result
    log_traffic(request, content=page)
    if request.user.is_authenticated:
        page.readers.add(request.user)
    return page.serve(request, *args, **kwargs)


@csrf_protect
def serve_search(request, slug=None):
    if slug is not None:
        try:
            search_query = SearchQuery.objects.get(slug=slug)
            query = search_query.keyword
            request.GET = QueryDict(query_string=f"q={query}")
        except SearchQuery.DoesNotExist:
            pass
    query = request.GET.get("q", None)
    if query not in [None, "", " "]:
        query = query.strip().lower()
        search_query, _ = SearchQuery.objects.get_or_create(keyword=query)
        log_traffic(request, content=search_query)
    SearchViewClass = pages_settings.PAGE_SEARCH_VIEW
    if SearchViewClass is None:
        return SearchView(template="simpel_pages/search.html")(request)
    else:
        return SearchViewClass.as_view()(request)


@csrf_protect
def serve_category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    site = get_current_site(request)
    site_root = RootPage.objects.get(site=site)
    real_model = request.GET.get("type", None)
    filters = dict()
    if real_model is not None:
        filters["real_model"] = real_model
    filters["category__slug__in"] = [category.slug]
    queryset = site_root.page.get_descendants().filter(**filters).live().order_by("-created_at")
    log_traffic(request, content=category)
    return ListView.as_view(
        queryset=queryset,
        paginate_by=pages_settings.ITEM_PER_PAGE,
        template_name="simpel_pages/category.html",
        extra_context={"object": category},
    )(request)


@csrf_protect
def serve_tag(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    site = get_current_site(request)
    site_root = RootPage.objects.get(site=site)
    real_model = request.GET.get("type", None)
    filters = dict()
    if real_model is not None:
        filters["real_model"] = real_model
    filters["tags__slug__in"] = [tag.slug]
    queryset = site_root.page.get_descendants().filter(**filters).live().order_by("-created_at")
    log_traffic(request, content=tag)
    return ListView.as_view(
        queryset=queryset,
        paginate_by=pages_settings.ITEM_PER_PAGE,
        template_name="simpel_pages/tag.html",
        extra_context={"object": tag},
    )(request)


def serve_tags(request):
    return ListView.as_view(
        queryset=Tag.objects.order_by("name"),
        paginate_by=pages_settings.CATEGORY_PER_PAGE,
        template_name="simpel_pages/tag_list.html",
    )(request)


def serve_categories(request):
    return ListView.as_view(
        queryset=Category.objects.order_by("name"),
        paginate_by=pages_settings.TAG_PER_PAGE,
        template_name="simpel_pages/category_list.html",
    )(request)


def pages_link_list(request):
    """
    Returns a HttpResponse whose content is a Javascript file representing a
    list of links to pages.
    """
    link_list = [(page.title, page.url) for page in Page.objects.all()]
    return render_to_link_list(link_list)

simpel_pages/templates/simpel_pages/base.html
{% extends 'base_site.html' %}
{% load i18n pages_tags pages_widget_tags %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        {% block main_content %}{% endblock main_content %}
      </div>
      <div class="col-lg-4">
        {% block sidebar_content %}
          {% popular_pages "Popular" %}
          {% category_list "Category" %}
          {% tags_list "Tags" %}
        {% endblock sidebar_content %}
      </div>
    </div>
  </div>
{% endblock content %}

simpel_pages/templates/simpel_pages/category.html
{% extends 'simpel_pages/base.html' %}
{% load i18n pages_tags %}

{% block breadcrumb-items %}
  <li class="breadcrumb-item"><a href="{% current_homepage %}">{% trans "Home" %}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'serve_category' %}">{% trans "Category" %}</a></li>
  {% for item in object.get_ancestors %}
    <li class="breadcrumb-item">
      <a href="{{ item.get_absolute_url }}">{{ item|truncatechars:60 }}</a>
    </li>
  {% endfor %}
  <li class="breadcrumb-item active" aria-current="page">{{ object }}</li>
{% endblock breadcrumb-items %}

{% block main_content %}
<h1>{{ object|title }}</h1>
{% if object.description %}
  <div>{{ object.description|safe }}</div>
{% endif %}
<div class="py-2">
  <strong>{% trans "Back to" %}</strong>:
  <a href="{% url 'serve_category' %}">{% trans "Category Index" %}</a>
</div>
<div class="my-3 border-bottom"></div>
<div>
  {% if object_list.count %}
    <div class="row">
      {% for page in object_list %}
        <div class="col-lg-6">
          {% include 'simpel_pages/includes/page.html' with page=page %}
        </div>
      {% endfor %}
    </div>
  {% else %}
    {% include 'simpel_pages/includes/no_results.html' %}
  {% endif %}
  {% if is_paginated %}
    {% include 'simpel_pages/includes/pagination.html' %}
  {% endif %}
</div>
{% endblock %}

simpel_pages/templates/simpel_pages/category_list.html
{% extends 'simpel_pages/base.html' %}
{% load i18n pages_tags pages_widget_tags thumbnail %}

{% block breadcrumb-items %}
  <li class="breadcrumb-item"><a href="{% current_homepage %}">{% trans "Home" %}</a></li>
  <li class="breadcrumb-item active" aria-current="page">{% trans "Category" %}</li>
{% endblock breadcrumb-items %}

{% block main_content %}
  <h1 class="mb-3">{% trans "Categories" %}</h1>
  <div>
    {% if object_list.count %}
      <div class="row">
        {% for item in object_list %}
          <article class="card border-0 col-lg-4">
            {% if item.thumbnail %}
              <a href="{{ item.get_absolute_url }}" title="{{ item }}">
                {% thumbnail item.thumbnail 736x420 crop as thumb %}
                <img class="card-img-top img-fluid" width="{{ thumb.width }}" height="{{ thumb.height }}" src="{{ thumb.url }}" alt="{{ page.title }}">
              </a>
            {% endif %}
            <div class="card-body">
              <h2 class="h4"><a href="{{ item.get_absolute_url }}">{{ item|title }}</a></h2>
              {% if item.description %}
                <div class="small">{{ item.description|safe|truncatechars:60 }}</div>
              {% endif %}
            </div>
          </article>
        {% endfor %}
      </div>
    {% else %}
      {% include 'simpel_pages/includes/no_results.html' %}
    {% endif %}
    {% if is_paginated %}
      {% include 'simpel_pages/includes/pagination.html' %}
    {% endif %}
  </div>
{% endblock main_content %}

simpel_pages/templates/simpel_pages/default.html
{% extends 'simpel_pages/detail.html' %}
{% load i18n pages_tags pages_widget_tags thumbnail %}

{% block content %}
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <article class="article px-3 px-md-0">
        <div class="text-center py-4">
          <h1 class="post-title">{{ object.title }}</h1>
          <div class="post-meta mb-3">
            <span>
            {% trans "Posted on" %}
            {{ object.created_at }}
            {% if object.category %}
              {% trans "in" %} <a href="{% url 'serve_category' slug=object.category.slug %}">{{ object.category|title }}</a>
            {% endif %}
            </span>
          </div>
        </div>
        {% if object.thumbnail %}
          <div class="mb-3">
            {% thumbnail object.thumbnail 960x540 crop as thumb %}
            <img class="img-fluid" width="{{ thumb.width }}" height="{{ thumb.height }}" src="{{ thumb.url }}" alt="">
          </div>
        {% endif %}
        {% if object.content %}
          <div class="post-body">
            {{ object.content|safe }}
          </div>
        {% endif %}
        {% if object.tags.count %}
          <div>
            <strong>{% trans "Tags" %}:</strong>
            {% for tag in object.tags.all %}
              <a href="{% url 'serve_tag' slug=tag.slug %}">{{ tag|title }}</a>
            {% endfor %}
          </div>
        {% endif %}
        {% if object.readers.count %}
          <div>
            <strong>{% trans "Readers" %}:</strong>
            {% for reader in object.readers.all %}
              <a href="#">{{ reader.get_full_name|title }}</a>
            {% endfor %}
          </div>
        {% endif %}
        <div class="my-3 border-bottom"></div>
        {% related_pages "Related Pages" object number=4 template_name='simpel_pages/widgets/page_related.html' %}
      </article>
    </div>
  </div>
{% endblock content %}

simpel_pages/templates/simpel_pages/detail.html
{% extends 'simpel_pages/base.html' %}
{% load i18n pages_tags pages_widget_tags thumbnail %}

{% block breadcrumb-items %}
  {% for item in object.get_ancestors %}
    <li class="breadcrumb-item">
      <a href="{{ item.get_absolute_url }}">{{ item.title|truncatechars:60 }}</a>
    </li>
  {% endfor %}
  <li class="breadcrumb-item active" aria-current="page">{{ object|truncatechars:60 }}</li>
{% endblock breadcrumb-items %}

{% block main_content %}
<article class="article">
  <h1 class="post-title">{{ object.title }}</h1>
  <div class="post-meta mb-3">
    <span>
    {% trans "Posted on" %}
    {{ object.created_at }}
    {% if object.category %}
      {% trans "in" %} <a href="{% url 'serve_category' slug=object.category.slug %}">{{ object.category|title }}</a>
    {% endif %}
    </span>
  </div>
  {% if object.thumbnail %}
    <div class="mb-3">
      {% thumbnail object.thumbnail 960x540 crop as thumb %}
      <img class="img-fluid" width="{{ thumb.width }}" height="{{ thumb.height }}" src="{{ thumb.url }}" alt="">
    </div>
  {% endif %}
  {% if object.content %}
    <div class="post-body">
      {{ object.content|safe }}
    </div>
  {% endif %}
  {% if object.tags.count %}
    <div>
      <strong>{% trans "Tags" %}:</strong>
      {% for tag in object.tags.all %}
        <a href="{% url 'serve_tag' slug=tag.slug %}">{{ tag|title }}</a>
      {% endfor %}
    </div>
  {% endif %}
  {% if object.readers.count %}
    <div>
      <strong>{% trans "Readers" %}:</strong>
      {% for reader in object.readers.all %}
        <a href="#">{{ reader.get_full_name|title }}</a>
      {% endfor %}
    </div>
  {% endif %}
</article>
<div class="my-3"></div>
{% related_pages "Related Pages" object number=4 template_name='simpel_pages/widgets/page_related.html' %}
{% if object.parent %}
  <div>
    <strong>{% trans "Back to" %}</strong>:
    <a href="{{ object.parent.get_absolute_url }}">{{ object.parent.title }}</a>
  </div>
{% endif %}
{% endblock %}

{% block sidebar_content %}
  {% recent_pages "Recent" %}
  {% popular_pages "Popular" %}
  {% category_list "Category" %}
  {% tags_list "Tags" %}
{% endblock %}

simpel_pages/templates/simpel_pages/home.html
{% extends 'simpel_pages/base.html' %}
{% load pages_tags pages_block_tags %}

{% block content %}
  {% for block in object.blocks.all %}
    {% render_block block %}
  {% endfor %}
{% endblock content %}

simpel_pages/templates/simpel_pages/index.html
{% extends 'simpel_pages/base.html' %}
{% load i18n pages_tags pages_widget_tags %}

{% block breadcrumb-items %}
  {% for item in object.get_ancestors %}
    <li class="breadcrumb-item">
      <a href="{{ item.get_absolute_url }}">{{ item.title|truncatechars:60 }}</a>
    </li>
  {% endfor %}
  <li class="breadcrumb-item active" aria-current="page">{{ object|truncatechars:60 }}</li>
{% endblock breadcrumb-items %}

{% block main_content %}
<h1>{{ object.title }}</h1>
{% if object.content %}
  <div>{{ object.content|safe }}</div>
{% endif %}
{% if object.parent %}
  <div class="py-2"><strong>{% trans "Back to" %}</strong>: <a href="{{ object.parent.get_absolute_url }}">{{ object.parent.title }}</a></div>
{% endif %}
<div class="my-3"></div>
<div>
  {% if object_list.count %}
    <div class="row">
      {% for page in object_list %}
        <div class="col-lg-6">
          {% include 'simpel_pages/includes/page.html' with page=page %}
        </div>
      {% endfor %}
    </div>
  {% else %}
    {% include 'simpel_pages/includes/no_results.html' %}
  {% endif %}
  {% if is_paginated %}
    {% include 'simpel_pages/includes/pagination.html' %}
  {% endif %}
</div>
{% endblock %}

simpel_pages/templates/simpel_pages/notfound.html
{% extends 'simpel_pages/base.html' %}


{% block content %}
  <h1>Not Found</h1>
{% endblock content %}

simpel_pages/templates/simpel_pages/search.html
{% extends 'simpel_pages/base.html' %}
{% load i18n pages_tags pages_widget_tags %}

{% block breadcrumb-items %}
  <li class="breadcrumb-item"><a href="{% current_homepage %}">{% trans "Home" %}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'serve_tag' %}">{% trans "Search" %}</a></li>
  {% if query %}
    <li class="breadcrumb-item active" aria-current="page">{{ query }}</li>
  {% endif %}
{% endblock breadcrumb-items %}

{% block main_content %}
    
    <form method="get" action="{% url 'serve_search' %}">
      <div class="input-group">
        <input class="form-control" type="search" name="q" id="searchInput" value="{{ query }}" placeholder="{% trans "Search Something ..." %}">
        <input class="btn btn-primary" type="submit" value="Search">
      </div>
    </form>
    
    {% if query %}
      <h1>{% trans "Search Results for" %} "{{ query }}"</h1>

      {% for result in page.object_list %}
          {% include 'simpel_pages/includes/page_list.html' with page=result.object %}
      {% empty %}
          <div>{% trans "No results found!" %}</div>
      {% endfor %}
      {% if page.has_previous or page.has_next %}
          <div>
            {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
            |
            {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
          </div>
      {% endif %}
    {% else %}
      {% recent_pages "Recent Pages" number=4 template_name='simpel_pages/widgets/page_related.html' %}
    {% endif %}
{% endblock %}